### ISSUE TITLE
sanitizer ?

### ISSUE THREAD

**Issue by setop** [phpdocker-io/readability-js-server#6]
Hi,

I wanted to play with Mozilla readability out of the browser and your project made it possible. Thanks a lot for that.

I modified the source to allow to POST html content, in addition to URL as it better fits to my use-case. Works well. If it has some value, I could make a PR.

I was wondering why DOMPurify, the HTML sanitizer, is used after readability and not before. If the content coming from the outside could be unsafe, it should not be passed to readability as is ? On the contrary, the content coming out of readability should be quite safe, isn't it ?

I'm about to move DOMPurify pass after readability pass or even get rid of it (the less dependencies, the better)...

Please tell me if I missed something.

Cheer

**Comment by dmchmk** [comment]
> I modified the source to allow to POST html content, in addition to URL as it better fits to my use-case. Works well. If it has some value, I could make a PR.

It would be very useful! But, it doesn't seem that original author of the project updates it often:(

**Comment by setop** [comment]
Hi @megavenik,

> It would be very useful! But, it doesn't seem that original author of the project updates it often:(

It was too complicated to contribute without the author. I created a new [code repository ](https://framagit.org/setop/readability-server) with code only fulfilling my needs.

**Comment by luispabon** [comment]
My apologies, I had turned off updates on this repository by accident and never got notifications on this issue. Please let me know if you wanna resuscitate this.

**Comment by dmchmk** [comment]
Absolutely!

**Comment by luispabon** [comment]
Done, thanks for your patience. Make sure you update to master if you're using the code directly, or to `phpdockerio/readability-js-server:1.4` (or even better, `phpdockerio/readability-js-server:1`) if you're using the docker image.

**Comment by drimacus182** [comment]
@luispabon Do you have any plans to add some functionality for taking html content as input in addition to url, as @setop described in first message? It would fit my use case better too.

@setop I was trying to find a fork with code that takes html as input, but I didn't find it among your repositories. If you don't mind, could you please publish it somewhere, it would definitely have value.

**Comment by setop** [comment]
>  If you don't mind, could you please publish it somewhere, it would definitely have value.

My [repo](https://framagit.org/setop/readability-server) is hosted on a gitlab instance, accessible if you login. You can connect with your github account if it suits you.

**Comment by drimacus182** [comment]
@setop Thanks a lot!
